=====================================
Menu: 
  AND term term ...                  
  OR term term ...                   
  DIFF term not-present-term not-present-term ... 
  PRINT page                         
  INCOMING page                      
  OUTGOING page                      
  QUIT                               
=====================================

search-shell (prompt) $: 
1
test-small/pgb.md

search-shell (prompt) $: 
